# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.68.1"

  on_macos do
    on_intel do
      url "https://get.trivy.dev/trivy?version=0.68.1&os=darwin&arch=amd64"
      sha256 "d5b5bd3b3c3626d223c3981cc40f4709f00a6327a681b588d2fc64a3aa9d02c5"

      def install
        bin.install "trivy"
      end
    end
    on_arm do
      url "https://get.trivy.dev/trivy?version=0.68.1&os=darwin&arch=arm64"
      sha256 "4dd3d2e74e1b6f6f7fd5fbf55489727698f586d6a6a0cff3421031a05b80bcac"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://get.trivy.dev/trivy?version=0.68.1&os=linux&arch=amd64"
        sha256 "63e37242088e418651931f891963c19554faa19f0591fe6b40b606152051df2f"

        def install
          bin.install "trivy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://get.trivy.dev/trivy?version=0.68.1&os=linux&arch=arm64"
        sha256 "b29ea550f573afbcae3c86fb2b5e0ebba76b7cb0965e3787c4e8cb884d2c1d57"

        def install
          bin.install "trivy"
        end
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
