# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/aquasecurity/trivy"
  version "0.64.0"

  on_macos do
    on_intel do
      url "https://github.com/aquasecurity/trivy/releases/download/v0.64.0/trivy_0.64.0_macOS-64bit.tar.gz"
      sha256 "f7c649c3e9598fde7074bb34b024d11f5b836d230c391a0cdde319db73e0fedc"

      def install
        bin.install "trivy"
      end
    end
    on_arm do
      url "https://github.com/aquasecurity/trivy/releases/download/v0.64.0/trivy_0.64.0_macOS-ARM64.tar.gz"
      sha256 "77e70dd2fdbac5986cc02a8def382bdaf78777f0050fc37af72916cc47b56a20"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aquasecurity/trivy/releases/download/v0.64.0/trivy_0.64.0_Linux-64bit.tar.gz"
        sha256 "e50755b3be29ae515091a45c96a2bc126846334210c30202331b797b9ae6e366"

        def install
          bin.install "trivy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aquasecurity/trivy/releases/download/v0.64.0/trivy_0.64.0_Linux-ARM64.tar.gz"
        sha256 "c7e78d67af98dad178f18b4b8d20929b7f9d267e9c556f8ad815f8997035bcd9"

        def install
          bin.install "trivy"
        end
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
