# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc ""
  homepage "https://github.com/aquasecurity/trivy"
  version "0.3.1"

  if OS.mac?
    url "https://github.com/aquasecurity/trivy/releases/download/v0.3.1/trivy_0.3.1_macOS-64bit.tar.gz"
    sha256 "6b3225573a7a46aa5fa7ac52e643c427373aba8771721ec5e52154fb7ea36fb0"
  elsif OS.linux?
    url "https://github.com/aquasecurity/trivy/releases/download/v0.3.1/trivy_0.3.1_Linux-64bit.tar.gz"
    sha256 "406c3447b80dfdcf0a302355e21869e3fa7f5a9a851d056916f8e4c945ec3a1b"
  end
  
  depends_on "rpm"

  def install
    bin.install "trivy"
  end

  test do
    system "#{bin}/program --version"
  end
end
